### PR TITLE
Added various icons by TraumaD91

### PR DESCRIPTION
**Pull request by quassy**

### CODE REVIEW

**Comment by cybre** [comment]
Steam game icons must be named as "steam_icon_[steamid].svg"

**Comment by mank319** [comment]
@quassy thanks for that huge addition. @cybre how about simply merging this now and creating symbolic links from each "real-name-icon" to `steam_icon_[steamid]`? This way the icons could be used for representations of those games installed in other ways than steam?

**Comment by cybre** [comment]
@mank319 That's a good idea, doesn't solve the "hardcoded" icons problem, though.

**Comment by mank319** [comment]
@cybre `hardcode-fixer` looks interesting. In fact, it does not seem as if we have to fork it as such, as it does not rely on a particular theme and we'd be better off contributing pull requests to the original list, so others benefit from it, aswell: https://github.com/Foggalong/hardcode-fixer/wiki/Theme-Support

**Comment by mank319** [comment]
I had a look at `hardcode-fixer`'s source code: It fetches the list from **Github** whenever you run the script, so we could include the shell script directly and wouldn't have to worry about keeping the list up-to-date. That being said, we'd have to watch out for changes in the script itself, so we better note the number of the latest commit at the time of inclusion. Maybe we could also solve that via `git submodules`, but I have no experience with that yet.

**Comment by cybre** [comment]
@mank319 @quassy The problem with that idea is that the fixer will "fix" all the launchers from the and thus brake every launcher for which we don't provide an icon.

**Comment by mank319** [comment]
Oh I see. Well then forking is the way to go I guess :wink:

**Pull request merged**
