### PR TITLE
new wingpanel preview in readme

### PR DESCRIPTION
**Pull request by RafaelCz**
screenshot_wingpanel

### CODE REVIEW

**Comment by cybre** [comment]
Wow, now that's a lot of indicators.

**Comment by cybre** [comment]
Thanks!

**Comment by RafaelCz** [comment]
no problem.
I thought, an actual preview would be nice.
BTW, these are not all icons...

**Comment by quassy** [comment]
> Wow, now that's a lot of indicators.

Maybe I will make a version where each indicator is explained so people can directly see which apps are supported.

**Pull request merged**
