### PR TITLE
Telegram Desktop indicator icons - second try :)

### PR DESCRIPTION
**Pull request by RafaelCz**
d8a1f0b0-f1f2-11e4-8524-479fff5cbafe
I can't check for the binary, because Telegram Desktop doesn't have a default install directory, so I'm checking for the default desktop entry, which is generated by default at the first start of the application.

### CODE REVIEW

**Comment by cybre** [comment]
Thanks for that!

**Comment by RafaelCz** [comment]
...and what about the scudcloud pull request?

**Comment by cybre** [comment]
I'll check it out in a moment.

**Comment by bil-elmoussaoui** [comment]
Well, this is not really the best idea.. as you can remove the telegram desktop file or rename it or anything else. You can look at the same time for the .TelegramDesktopFolder and in /usr/share/applications

**Comment by RafaelCz** [comment]
If you remove it, Telegram Desktop will recreate it by the next start.

**Comment by bil-elmoussaoui** [comment]
Nop, it will recreate it by the next update. You can try it

**Comment by cybre** [comment]
We can check for `icomute_22_0.png`.

**Comment by cybre** [comment]
I guess if there are unread messages, telegram will create a icomute_22_{number of messages}.png so we can't check for the default `icomute_22_0.png`.

**Comment by cybre** [comment]
Can we look for `/home/cybre/.TelegramDesktop/tdata/settings0`?

**Comment by bil-elmoussaoui** [comment]
+ Telegram dosen't support tray icon in XFCE, the best thing is to not look for anything and just copy the folder icons to .TelegramDesktop

**Comment by cybre** [comment]
@bil-elmoussaoui We must look for something, we don't want Telegram Desktop listed in the installer if it's not installed. Also, we're targeting elementary OS Freya, so we have nothing to do with XFCE.

**Comment by bil-elmoussaoui** [comment]
Well, if it's the case you can look for anything in .TelegramDesktop/tdata

**Comment by cybre** [comment]
So, `/home/username/.TelegramDesktop/tdata/settings0` it is.

**Comment by RafaelCz** [comment]
@cybre 
we can't look for `/home/username/.TelegramDesktop/tdata/settings0`, i don't have one my setingre stored in `settings1`
I'm gonna change it to /home/username/.TelegramDesktop/tdata7icon.png`, this is the only static file in there.

**Comment by cybre** [comment]
@RafaelCz Oh, ok. No need to change it now, already on it.

**Comment by RafaelCz** [comment]
I guess the setting-scounter raises, when someone logs off and on again, or logs in with another account
@cybre while you are at it, you also could remove the directory-check in `telegram_desktop/setup.sh`, since we are checking for it in the installer itself...

**Comment by cybre** [comment]
@RafaelCz Sure!

**Pull request merged**
