### PR TITLE
Classic Menu indicator icon

### PR DESCRIPTION
**Pull request by RafaelCz**
classicmenu

### CODE REVIEW

**Comment by quassy** [comment]
The little arrow next to it is weird, don't you think? All indicators are expandable / clickable / "hide" something, so no need to emphasize that.

**Comment by RafaelCz** [comment]
It was a 3 minute nobrainer remake of the original icon.

**Comment by RafaelCz** [comment]
classicmenu
this one is way better

**Comment by cybre** [comment]
I agree @RafaelCz

**Pull request merged**
