### PR TITLE
Telegram Desktop indicator icons

### PR DESCRIPTION
**Pull request by RafaelCz**
I figured out how to change the Telegram Desktop indicator icons.
bildschirmfoto vom 2015-05-03 23 47 42

It's not the usual way by placing some correctly named images into the theme.
Telegram is one huge and ugly static built binary blob, it generates it's own indicator images for each number of unread messages into `~/.TelegramDesktop/tdata/ticons`.
It's save to replace the generated images, once created, Telegram reuses them.
I created only one image for unread messages and linked the other 98 (yes, the indicator displays up to 99 unread messages) to this one.
Here is the responsible [function for creating the icons](https://github.com/telegramdesktop/tdesktop/blob/aeb2ec68efeb1a66782fc90fd3a05518b82b9de8/Telegram/SourceFiles/pspecific_linux.cpp#L267-L285).

So... what do you guys think?

### CODE REVIEW

**Comment by quassy** [comment]
I think you should also file a bug at Telegram and tell them they are stupid :p

Wondering about the dot that indicates a new message / notification: Is the position defined somewhere? Some icons seem to have it on the top right, some on the bottom right. Could look weird if you have several icons with new notifications next to each other.

**Comment by RafaelCz** [comment]
Till now I've seen the blue dot only in the upper right corner. I couldn't find any guideline for the position, so I'm trying to stay consistent.

**Comment by fsvh** [comment]
maybe can we create a group in telegram and like this communicate faster? @quassy  @RafaelCz  @cybre @mank319

**Comment by quassy** [comment]
I personally would prefer [Gitter](https://gitter.im/mank319/elementaryPlus) because it has some nice GitHub integration (and also Markdown support etc).

**Comment by cybre** [comment]
Needs fixing to accommodate the new updates to the installer. (Please create a new pull request when you're done fixing)

**Pull request closed without merging**
