### PR TITLE
Add insync icons, fixes #52

### LINKED ISSUE #52: Icon Request: Insync
[Insync](https://www.insynchq.com/) is the most feature-rich Google Drive client on Linux and comes with the following tray indicator:

image

### PR DESCRIPTION
**Pull request by RafaelCz**
bildschirmfoto vom 2015-05-14 10 38 33
preview-app
preview-places
output

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Really amazing work!!!!! If you can use the indicator icons for gdrive and add this to the script installer too ;)
The grive (Google drive) uses this folder for icons : /opt/thefanclub/grive-tools/icons/dark and light version

**Comment by RafaelCz** [comment]
@bil-elmoussaoui  of course it could be done, but there is a problem: Grive is dead.
- the maintainer abandoned the project, the last commit was 2 years ago (plenty of errors, 27 waiting pull requests...)
- it's using a deprecated API, which is going to be shut down by Google
- because of the API changes, the creators of grive-tools (graphical frontend for grive) stopped their project as well

**Comment by bil-elmoussaoui** [comment]
@RafaelCz I didn't knew about this , really sad i will abandon Grive soon then :-(

**Comment by bil-elmoussaoui** [comment]
@RafaelCz for the smallest sizes of the folder it would be better if you add the google drive logo as those icons will be used here : 
capture du 2015-05-18 17 23 50

**Comment by RafaelCz** [comment]
@bil-elmoussaoui maybe I'm going to change it. It won't be used anyways, pantheon doesn't support custom folder-icons... I did it only because there was a folder-icon bundled with the app and I wanted to make it complete.

**Comment by bil-elmoussaoui** [comment]
@RafaelCz Well ,if you use an other file manager instead of pantheon files the icons will works fine ;) 
and maybe we will have this feature in a future update who knows!! Thank you anyway

**Pull request merged**
