### PR TITLE
Update README with PPA instructions

### PR DESCRIPTION
**Pull request by cybre**

### CODE REVIEW

**Comment by orschiro** [comment]
Thanks for the ppa support! I followed the instructions but encountered the following warning. 

```
Preparing to unpack .../elementaryplus_1.0+107+19~ubuntu14.04.1_all.deb ...
Unpacking elementaryplus (1.0+107+19~ubuntu14.04.1) ...
Setting up elementaryplus (1.0+107+19~ubuntu14.04.1) ...
/usr/share/glib-2.0/schemas/apps.elementaryPlusInstaller.gschema.xml: Error on line 4 char 1: <schema id='apps.elementaryPlusConfigurator'> already specified.  This entire file has been ignored.
```

Safe to be ignored?

**Comment by cybre** [comment]
Yeah, that's because you already have the schema installed (You've used the
installer before).

**Comment by cybre** [comment]
The next update (in a few minutes) is going to remove the old schema.

**Comment by orschiro** [comment]
@cybre Thanks for clarifying! All working now.

**Pull request merged**
