### PR TITLE
prime-indicator status icons

### PR DESCRIPTION
**Pull request by ReplicaObscura**
This replaces the nvidia.png and intel.png notify icons included with the prime-indicator package.

The old icons, while somewhat monochrome, had too much shadowing and were too large in the indicator area compared with elementary's other icons.

These new icons are the original icon files, with the canvas resized to square, then the entire icon has heavy brightness and contrast added to make them almost pure white. Then I resized bicubic to 24px, and got a pretty good result (much better than before at least).

I figured I'd share for anyone else using prime-indicator!

### CODE REVIEW

**Comment by bmcclure** [comment]
I added a little bit of extra brightness and contrast as the icons still look just slightly grayish compared to the other indicators. This helped somewhat.

**Comment by bmcclure** [comment]
I also didn't like that the nvidia logo looked too 3D with its beveled edges on the square part of the logo. I went ahead and chopped 1 pixel off around the top, right, and bottom to give the icon a flatter appearance.

**Comment by bmcclure** [comment]
Here's an example showing the icon in use on my system:

indicators

**Comment by quassy** [comment]
Thank you and sorry for the very late merge.

**Pull request merged**
