### PR TITLE
Added Hangouts and MEGA icons, fixes #240 & #371

### LINKED ISSUE #240: Icon request: MEGASync
Icon name: mega
Original icon:
mega

### PR DESCRIPTION
**Pull request by TraumaD**
hangouts
Hangouts Icon

mega
MegaSync Icon

### CODE REVIEW

**Comment by TraumaD** [comment]
I hope I did this right I'm super new to Github. Let me know If I need to do something else.

**Comment by cybre** [comment]
The icons look good. Thanks for the contribution!
For next time: 
* Open one PR per app
* Don't commit the icons separately; just add them all and commit once. Any later fixes should be in separate commits.

**Comment by TraumaD** [comment]
Ok so one PR per icon added/changed, and add all the icons at once with one commit for all of them? So I tried to add them all at once first but the github web interface won't let me upload folders. Am I going to need to learn to use git from the terminal to add them all at once? Also should I reference the bugs it fixes in the commits or the PR or both? I noticed after I referenced them in the commits a notification thing popped up under the bug. Thanks, and again sorry I'm such a noob at this.

**Comment by cybre** [comment]
Using `git` is very easy (at least the parts you need).
Configure it with 
```
git config --global user.name 'Your Name'
git config --global user.email 'you@example.com'
```
You'll only need to do that once.


Clone your fork: `git clone https://github.com/TraumaD/elementaryPlus.git`
Create a new branch: `git checkout -b branchname` (branchname could be the app name)
Make your changes and add the files: `git add 16/icon.svg 24/icons.svg ...`

Run `git status` to make sure everything is OK.

Commit with `git commit -m "Your commit message, fixes #123"`
Push with `git push original branchname`

Then go to the repo page and click the “New Pull Request” button.

Ta-da :)

Also, only reference the issue in the first (main) commit. (Not the PR title)

**Comment by TraumaD** [comment]
@cybre Thank you very much I'm super new to all of this and this helps a lot. I hope to contribute more very soon.

**Pull request merged**
