### PR TITLE
Add Software Center and Nvidia Settings icons

### PR DESCRIPTION
**Pull request by TraumaD**
Preview of Icons Added:
software-center-preview

### CODE REVIEW

**Comment by cybre** [comment]
"Add Nvidia-Settings Icon"
heh, we have a rogue commit :)

**Comment by TraumaD** [comment]
Woops I have no idea how that happened.

**Comment by cybre** [comment]
I'll just merge this one and dismiss the other one.
The icons look great, though! Thanks!

**Comment by cybre** [comment]
Oh, GitHub dismissed it automatically. Nice.

**Pull request merged**
