### PR TITLE
Synapse indicator icon

### PR DESCRIPTION
**Pull request by RafaelCz**
synapse

### CODE REVIEW

**Comment by quassy** [comment]
Wouldn't a magnifying glass be a better fit?

**Comment by cybre** [comment]
@quassy Well, no. You can't search with this indicator, this is the "real"
synapse indicator. It's another one of those unnecessary indicators.

**Comment by quassy** [comment]
> It's another one of those unnecessary indicators.

*Sigh.* So what does it do?

**Comment by RafaelCz** [comment]
@quassy It's an application launcher, comparable to gnome do. Here is a
german description: https://wiki.ubuntuusers.de/Synapse
Am 07.06.2015 19:12 schrieb "quassy" <notifications@github.com>:

**Comment by quassy** [comment]
Well from [this, quote old article](http://www.webupd8.org/2013/06/synapse-indicator-new-search.html) the indicator actually does not only search for applications but also files (and possibly more).

**Comment by cybre** [comment]
@quassy, Synapse and Synapse Indicator (uses the synapse api) are two
separate apps.

**Comment by cybre** [comment]
This is the "synapse" indicator, not "synapse indicator" indicator.

**Comment by cybre** [comment]
This is the "synapse launcher" indicator, not "synapse indicator" indicator.

This is the indicator in question:
menu_003

**Comment by RafaelCz** [comment]
I picked a confusing name for this commit :)

**Comment by cybre** [comment]
I think this is clear, going to merge now.

**Pull request merged**
