### PR TITLE
#62

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This will fix this bug by checking if the gtk version is 3.14 or newer

### CODE REVIEW

**Comment by cybre** [comment]
Looks good to me. I'll review it as soon as I get home. Thanks!

**Comment by bil-elmoussaoui** [comment]
@cybre this will fix #62  too , but i didnt add Megasync and OwnCloud folders if you can add them before merging this it will be cool ;)

**Comment by bil-elmoussaoui** [comment]
This is ready to go ;)

**Comment by cybre** [comment]
Not quite, s/compenents/components

**Comment by cybre** [comment]
I feel like we should search for binaries instead of directories for detecting installed applications.

**Comment by cybre** [comment]
We can easily do this with isfile().

**Comment by bil-elmoussaoui** [comment]
@cybre i did used apt module to check if a package is installed

**Comment by cybre** [comment]
That's not going to work for non-ubuntu distro's.

**Comment by cybre** [comment]
Eh, using apt will fails on non-ubuntu based distro's.

**Comment by cybre** [comment]
Also, you should split this pull request into two separate pull request (one for #55 and one for #62)

**Comment by bil-elmoussaoui** [comment]
Can you check this now?

**Comment by cybre** [comment]
As I said, there's no need for using apt to check if the app is installed. The installer should presume the app is installed if the app binary is present. And please create new pull request for the two issues. This one has become messy and there are some conflicts.

**Comment by bil-elmoussaoui** [comment]
Ok, i created a pull request for the other issue. I didn't understand what you mean by checking the app binary; did you only mean the executable file ?

**Comment by cybre** [comment]
Exactly.

**Comment by bil-elmoussaoui** [comment]
I will close this and open a new one.

**Pull request closed without merging**
