### PR TITLE
indicator-cpufreq icons

### PR DESCRIPTION
**Pull request by RafaelCz**
cpufreq

### CODE REVIEW

**Comment by cybre** [comment]
I'm not sure abou these. What do you think @mank319 @quassy?

**Comment by RafaelCz** [comment]
What exactly don't you like about it?
I've been trying to stay as close as possible to the original icon, because the only alternative, that I came up with, was a boring rectangle...
indicator-cpufreq

**Comment by mank319** [comment]
I think it looks a bit more detailed than most of the other indicator icons.
Have you tried replacing the bars in the middle by one single bar that varies only in height?

**Comment by cybre** [comment]
Well, firstly, I find the base colour (the transparent part) to be a bit
off. It looks like it's disabled (like the bluetooth indicator to the right
of the wifi icon). And what @mank319 said.

**Comment by cybre** [comment]
Also, you don't have to stay close to the original. Just make it recognizable.

**Comment by RafaelCz** [comment]
I know, but as I said, the alternative, I came up with, was a boring rectangle... which was a bit too simple for my taste.

**Comment by mank319** [comment]
To be honest this fits a lot better than the actual original icon and if nobody proposes and alternative, I'd suppose we still merge it!

That said you might give it one more try - if you feel like doing so :wink:

Maybe you could somewhat resemble the structure of the battery indicator, with a different aspect ratio and the little pins directly attached to the background?

**Comment by RafaelCz** [comment]
give me a few minutes, i'll try some alternative versions based on your suggestions

**Comment by mank319** [comment]
Great! I'm looking forward to see your result!

It may take me a while to answer though, as I am going to sleep now :zzz: - just so you don't wonder about the lack of immediate feedback :wink:

**Comment by RafaelCz** [comment]
no problem... I'm going to hit the pillow aswell
bildschirmfoto vom 2015-05-25 01 46 35
transparency and bars are gone

**Comment by cybre** [comment]
Now this looks much better. We'll have to wait for @mank319's opinion,
though.

**Comment by quassy** [comment]
To me the new version looks good :)

**Comment by mank319** [comment]
Very nice! Thank you for your great work and your cooperation :wink:

**Pull request merged**
