### PR TITLE
Fix #62

### LINKED ISSUE #62: Problem installing the Spotify icons when Spotify is not installed
Hi,

i forgot, that i did not install spotify on my new system and started to install elementaryPlus. The installer went grazy and started to loop endlessly. There should be a check, if the app is installed!

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Well, this will check only if spotify exists. You can manually add/remove any other applications as i didn't find the executable file of : Skype,Megasync,OwnCloud

### CODE REVIEW

**Comment by cybre** [comment]
s/compenents/components

**Comment by bil-elmoussaoui** [comment]
Done :)

**Comment by cybre** [comment]
Your changes have been merged in #96 (This pull request has some conflicts). Thanks!

**Comment by bil-elmoussaoui** [comment]
You're welcome ! i would be happy if i can fix anything else.

**Pull request closed without merging**
