### PR TITLE
Sound switcher indicator icon

### PR DESCRIPTION
**Pull request by RafaelCz**
soundswitcher

### CODE REVIEW

**Comment by RafaelCz** [comment]
Or do you prefer a simple symbolic headphone jack?
screenshot2

**Comment by quassy** [comment]
> I like the alternative icon, but it may be a bit too simple...

Dito. Also it leaves out the functionality of sound switching which is shown done in the first icon. I'd prefer merging this as it is.

**Comment by cybre** [comment]
The first one is definitely better.

**Comment by cybre** [comment]
@mank319 What do you think?

**Comment by cybre** [comment]
Going to merge this as @mank319 is very busy at the moment.

**Comment by mank319** [comment]
Thanks @RafaelCz for another great contribution!

And thanks @cybre for taking care of it - Also I'd agree on the choice you made there :wink:

**Pull request merged**
