### PR TITLE
BitTorrent Sync GUI indicator icons

### PR DESCRIPTION
**Pull request by RafaelCz**
bildschirmfoto vom 2015-04-26 21 58 26
1. connected (there are 12 of them for a rotating animation during sync)
2. connecting
3. paused
4. disconnected

### CODE REVIEW

**Comment by RafaelCz** [comment]
Deluge & Transmission indicator icons added
bildschirmfoto vom 2015-04-27 01 47 13

**Comment by RafaelCz** [comment]
Atom editor app icons
preview

**Comment by bil-elmoussaoui** [comment]
Good work!! Hope you add more indicator icons ;)

**Comment by quassy** [comment]
@RafaelCz FYI: If you create a seperate branch for each significant change you make (e.g. one branch `add-bittorrent-sync`, one `add-atom`, etc...) the pull requests can be made separate as well. Not that I see anything wrong with your submissions (in fact they look great!) but *if* there was a problem with one of the submissions this would make it easier to accept some changes and improve the others. I would merge this PR in a second if I could test the indicators :)

**Comment by RafaelCz** [comment]
@quassy Thanks for the hint... i thought I got it now, but it seems that I didn't :)
I created a new branch named `add-sparkleshare-indicator`, added my commit to this branch and created a pull request. But now there are all 5 commits (my new one and the four previous commits) attached to this pull request.
Sorry for the mess :/

**Comment by RafaelCz** [comment]
I guess I understand, what I did wrong... I am closing my pull requests and recreating them in a proper and (hopefully) separated way. Sorry again for the inconvenience, this is my first real contact with git :(

**Comment by quassy** [comment]
No worries! I believe you have forgot [Syncthing](https://github.com/RafaelCz/elementaryPlus/commit/9151c13d3e0f3b96670f36ac49c74a013baf3ff2)?

**Comment by RafaelCz** [comment]
No I have not, I only confused the commit messages :)
In fact I already have a elementary styled Syncthing indicator icon waiting for deployment.
The thing is, Syncthing GTK ignores any icons provided by the icon theme, but according to [this commit](https://github.com/syncthing/syncthing-gtk/commit/29a70199c8825d73fd2a52ba51d1cd939a3dd327) the next version should be supporting icon theming.

**Pull request closed without merging**
