### PR TITLE
Sublime text icon enhanced

### PR DESCRIPTION
**Pull request by fsvh**
Hope you like. The 16x16 can be removed if you don't like it.

old
sublime-text

new
sublime-preview

### CODE REVIEW

**Comment by quassy** [comment]
Could you also add 24px? :)

**Comment by fsvh** [comment]
@quassy yup I can:)

**Comment by fsvh** [comment]
@quassy done! I added the size 24x24.

**Comment by mank319** [comment]
Being a Sublime user myself, I really appreciate that :wink:

**Comment by julihermes** [comment]
very good improvement!! Thanks!! :)

**Comment by Heart1010** [comment]
:+1:

**Comment by julihermes** [comment]
I have a question, to update my installation, I just have a pull and run the script again?

**Pull request merged**
