### PR TITLE
New installer design

### PR DESCRIPTION
**Pull request by cybre**
screenshot from 2015-06-14 14 26 48
screenshot from 2015-06-14 14 27 15

What do you guys think? @mank319 @quassy

### CODE REVIEW

**Comment by mank319** [comment]
I really like it!

**Comment by cybre** [comment]
screenshot from 2015-06-14 16 44 11
screenshot from 2015-06-14 16 44 24
screenshot from 2015-06-14 16 44 37

**Comment by quassy** [comment]
Looks great! 

Only thing that comes to mind: I'd not rely on hover text, so the greyed out entries should also have a `(app not installed)` behind the app name. 

What is the download button for (top right)?

**Comment by cybre** [comment]
@quassy That's the minimize button :)

**Comment by cybre** [comment]
@quassy Like this?
screenshot from 2015-06-14 17 17 23

**Comment by quassy** [comment]
Yep :)

**Comment by cybre** [comment]
So, shall I merge it?

**Comment by mank319** [comment]
You surely have my vote @cybre :wink:

**Pull request merged**
