### PR TITLE
Add teamviewer status icons adapted from Numix

### PR DESCRIPTION
**Pull request by elmat0**
As requested [here.](https://github.com/mank319/elementaryPlus/issues/335)

Original SVG icons from Numix (credited) with the colours adjusted to match elementary status icons. PNG images generated with hardcode-tray. Unsure if you also want the svgs?

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
You will need to update the python file too https://github.com/mank319/elementaryPlus/blob/master/scripts/elementaryplus-installer.py

**Comment by elmat0** [comment]
I was hoping someone that knew what they were doing (read: @cybre ;p) could take care of that.

**Comment by quassy** [comment]
Is there more to do than add the following?

```
    [
        "Teamviewer",
        "teamviewer", # guess
        "/usr/bin/teamviewer",
        "TeamViewer is a software package for remote control, desktop sharing, online meetings, web conferencing and file transfer between computers.",
        "teamviewer",
        "standard"
    ],
```

**Comment by cybre** [comment]
@quassy yup. That's it

**Comment by cybre** [comment]
Ah forgot about the .desktop launcher issue. I'll write a script that fixes the launcher as well as the indicator icons.

**Pull request merged**
