### PR TITLE
Add Audacious Icon

### PR DESCRIPTION
**Pull request by libredeb**
Add Audacious icon

### CODE REVIEW

**Comment by cybre** [comment]
As multiple people already told you on Google+, please change the "a". You don't have to mimic the original icon.

**Comment by elmat0** [comment]
Thanks for the proposal @libredeb. I'm neither here nor there on the "a" and leave that to the rest of you to figure out. 

If you are going to use circles or squares I suggest using [these](https://github.com/elmat0/icons_etc/tree/master/templates) templates as a starting point in an effort at consistency. Also have a look into [pixel fitting](http://dcurt.is/pixel-fitting) as it seems really important for clarity at smaller scales.

Assuming you are using Inkscape you should reduce the file size by using the "path -> simplify" command on shapes (the a has a lot of superfluous nodes) and saving as an optimised svg rather than an inkscape svg.

**Comment by libredeb** [comment]
@cybre already did a survey in G+... most people vote for the option that I commit. Do not be crybaby!!!
@elmat0 I'm no expert on designing icons, but I think that this icon was quite good. For personal reasons stop using Elementary, it is not very stable and it bothers me. You could add the request pull to the master branch and from there make yourself the "path -> simplify" ???
Thanks!

**Comment by cybre** [comment]
I'm sorry? How am I being a "crybaby", exactly? You do know what criticism is, right? Your icon ignores the basic elementary OS guidelines and the "a" is seriously appaling. Change it.

**Comment by elmat0** [comment]
@libredeb there is no need to take things personally, I was providing what I considered constructive criticism.

**Comment by libredeb** [comment]
@elmat0 yes, you are helping me in something that totally unknown... thanks for that! but... I will not allow ignorance and disrespect of @cybre that for your information, I am more aware of HIG that you bitch!

**Comment by cybre** [comment]
Come back once you learn how to respect other people.

**Pull request closed without merging**
