### PR TITLE
new ownCloud indicator icons

### PR DESCRIPTION
**Pull request by RafaelCz**
owncloud

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
@RafaelCz older versions of OwnCloud are not hardcoded.. the best thing is to keep the icons in status too, what do you think?

**Comment by RafaelCz** [comment]
I kept them, the unnecessary 16px & 48px links are gone.

**Comment by cybre** [comment]
Didn't we agree we should rename the icons (for patched sni-qt) to work out of the box?

**Comment by RafaelCz** [comment]
@cybre without checking "use monochrone icons"?

**Comment by cybre** [comment]
@RafaelCz yes.

**Comment by RafaelCz** [comment]
Ok, I'll change it

**Comment by cybre** [comment]
For reference:
```
state-connecting:  9d626aa048ccbd28c9a5bf6bbaadee43.png
state-ok:          a4d0f4e492fad2e38e62dc68de83aaa0.png
state-sync:        23064844cb89c0654026212a3faa910f.png
state-pause:       4c8bee6fca0c59f47088f37c25880a24.png
state-error:       6a85c1b1eca5f176490afbea40b5a85b.png
state-information: e9b111ea19684326fa5140f7d14b215b.png
```

**Comment by RafaelCz** [comment]
there they are

**Comment by cybre** [comment]
Thanks!

**Pull request merged**
