### PR TITLE
Emblem icons for Pantheon Files Dropbox-Plugin and Synthing GTK

### PR DESCRIPTION
**Pull request by RafaelCz**
emblems
These are the missing emblem icons for the [pantheon files dropbox-plugin](https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+sourcepub/3595592/+listing-archive-extra). I also added the emblem icons for Syncthing

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Insync uses emblem icons too : https://github.com/numixproject/numix-icon-theme/issues/250

**Comment by RafaelCz** [comment]
a ridiculous amount of emblem icons...

**Comment by bil-elmoussaoui** [comment]
I don't use Insync, just in case you want to symlink the existing icons ;)

**Comment by RafaelCz** [comment]
i gonna do, as soon as I find out what a des error is

**Comment by RafaelCz** [comment]
Insync emblem icons added. They won't work until Insync starts supporting pantheon (they are going to, according to their support forums).
I simplified them, Insync tries to put way too much information in these tiny icons.

**Pull request merged**
