### PR TITLE
tweetdeck improve

### PR DESCRIPTION
**Pull request by fsvh**
I did an icon for tweetdeck hope you like it. 

Here's a preview. Let me know what do you think about this.

tweetdeck

### CODE REVIEW

**Comment by mank319** [comment]
Good job :+1:
I personally prefer your version @fsvh :wink: 

But as your pull request overrides an existing icon, I would appreciate the opinions of @quassy and @cybre.

The current one looks like this, in case you were wondering:

tweetdeck

**Comment by fsvh** [comment]
@mank319 sure I understand! =)

The actually looks good too. =)

**Comment by quassy** [comment]
I prefer the new ones too, they are closer to the original and have better contrast. Good work :)

Maybe the 16px could lose some more detail / have a bigger contrast for the outlines to become a bit clearer?

**Comment by fsvh** [comment]
@quassy I will check the 16px tweetdeck icon if I can improve

**Comment by quassy** [comment]
@cybre What do you think regarding the Tweetdeck icon?

**Comment by cybre** [comment]
@quassy Sorry for the late reply (went camping for 3 days).
The new icon looks great! I'm all in for replacing the current one.

**Pull request closed without merging**
