### PR TITLE
Reduze file sizes by cleanup

### PR DESCRIPTION
**Pull request by quassy**
Use Inkscape "Clean up Document" function (removes unused elements) on files >= 8 KiB to reduce overall file sizes by around 30 %. The elementaryPlus directory size shrinks from 8.30 MiB (9.52 MiB on disk for me) to 6.01 MiB (7.28 MiB), so about 28 % (24 %).

### CODE REVIEW

**Comment by quassy** [comment]
I still feel file sizes could be reduced by removing loads of whitespace as few sane people actually view svg's as plain text and not in an image editor. Maybe another time. 

Theoretically saving as plain svg would also reduce file sizes, but also make it harder to modify files, so I don't think this is an option.

**Comment by quassy** [comment]
@RafaelCz @mank319 @cybre What do you think?

**Comment by cybre** [comment]
I'm OK with this (although I don't know much about SVGs)

**Comment by RafaelCz** [comment]
I'm already optimizing my commited SVGs.

**Comment by quassy** [comment]
Yes I saw that when I tried to optimize yours ;). It was mostly old files that were lacking optimization.

**Comment by RafaelCz** [comment]
I'm using [Scour](https://github.com/oberstet/scour), it is more efficient than Inkscape.

**Comment by quassy** [comment]
Does Scour preserve the Inkscape metadata in Inkscape SVGs?

**Comment by RafaelCz** [comment]
You can set `--keep-editor-data` to keep them, but there is no reason for that. I have been removing everything from my SVGs and they are fine.

**Comment by quassy** [comment]
Yes for viewing it does not matter but if you include special shapes like stars they get converted to simple paths with plain svg and make it harder to re-edit with Inkscape... I'll try to run Scour over all files when I find the time and compare.

**Comment by quassy** [comment]
So I tried scour on all files, it reduces the total size from 9.2 MB to 5.0 MB with default settings and to 4.6 MB MB with maximum settings. At first sight all the files seem to be looking fine, but I wonder if there is an automated test to compare svg to make sure this does not degrade quaility.

**Comment by quassy** [comment]
This prevents other PRs from merging, so I'm gonna close this for now as the best way to proceed has not been decided upon yet.

**Pull request closed without merging**
